# Allow kube-rbac-proxies to create tokenreviews to check Prometheus identity when scraping metrics.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${ASSET_SHORT_PREFIX}-node-kube-rbac-proxy-binding
subjects:
  - kind: ServiceAccount
    name: ${ASSET_PREFIX}-node-sa
    namespace: ${NODE_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: ${ASSET_SHORT_PREFIX}-node-kube-rbac-proxy-role
  apiGroup: rbac.authorization.k8s.io
