kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${ASSET_SHORT_PREFIX}-csi-storageclass-reader-resizer-binding
subjects:
  - kind: ServiceAccount
    name: ${ASSET_PREFIX}-controller-sa
    namespace: ${NODE_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: openshift-csi-resizer-storageclass-reader-role
  apiGroup: rbac.authorization.k8s.io
