# Allow the controller to run privileged pods

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-smb-controller-privileged-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: smb-privileged-role
subjects:
- kind: ServiceAccount
  name: smb-csi-driver-controller-sa
  namespace:  ${NODE_NAMESPACE}
