apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ${ASSET_PREFIX}-node-metrics-serving-cert
  labels:
    app: ${ASSET_PREFIX}-node-metrics
  name: ${ASSET_PREFIX}-node-metrics
  namespace: ${NODE_NAMESPACE}
spec:
  ports:
  selector:
    app: ${ASSET_PREFIX}-node
  sessionAffinity: None
  type: ClusterIP
